alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gaa='git add -A;git commit -a -m '$2''
alias gpo='git pull origin master'
alias gpu='git fetch origin -v; git fetch upstream -v; git merge upstream/master'
alias gfu='git pull --rebase upstream master'
alias gs='git status -sb'
alias gc='git commit'
alias gca='git commit -a'
alias gco='git checkout'
alias gb='git branch'
alias gd='git diff'
alias greset='git reset --hard HEAD~1'
alias grv='git remote -v'
alias gst='git status'
alias gdiff='git vimdiff'
alias merge-to="!f() { git checkout $1 && echo git merge $2 && echo git checkout -; }; f"
